import assert from 'node:assert/strict';
import { parsePrivateCheckpointResponse as parse } from '../src/tools/handoff-context.js';
const routing = { channel: 'example-channel', replyTarget: null };
const args = { summary: 'Complete the synthetic task.', nextSteps: ['Verify fixture'], continue: true };
const call = { type: 'toolCall', name: 'handoff_context', arguments: args };
const expected = parse([call], routing);
assert.deepEqual(parse([{ type: 'thinking', text: 'Synthetic private reasoning' }, { type: 'text', text: 'Saving now.' }, call], routing), expected);
assert.deepEqual(parse([call, call], routing), expected);
assert.deepEqual(parse([{ ...call, arguments: JSON.stringify(args) }], routing), expected);
assert.deepEqual(parse([{ type: 'text', text: JSON.stringify(args) }], routing), expected);
assert.deepEqual(parse([{ type: 'text', text: 'Here is the checkpoint:\n```json\n' + JSON.stringify(args) + '\n```' }], routing), expected);
assert.deepEqual(parse([{ type: 'toolCall', name: 'unrelated', arguments: {} }, call], routing), expected);
assert.throws(() => parse([{ type: 'text', text: 'Just trust me.' }], routing), /usable summary/);
assert.throws(() => parse([{ type: 'thinking', text: JSON.stringify(args) }], routing), /usable summary/);
assert.throws(() => parse([{ ...call, arguments: { ...args, summary: '' } }], routing), /usable summary/);
assert.throws(() => parse([{ ...call, arguments: { ...args, summary: 'x'.repeat(12001) } }], routing), /usable summary/);
assert.throws(() => parse([call, { ...call, arguments: { ...args, summary: 'A different task' } }], routing), /conflicting/);
assert.equal(expected.handoff.routing.channel, 'example-channel');
console.log('PASS private checkpoint presentation tolerance and data validation');
