import assert from "node:assert/strict";
import { EventEmitter } from "node:events";
import { mkdtempSync,rmSync,writeFileSync } from "node:fs";
import type { IncomingMessage } from "node:http";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { DEEPGRAM_THOUGHT_CONTINUATION_MILLISECONDS,DeepgramVoiceTranscriptionProvider,type RealtimeSocket,type VoiceProviderTimerScheduler } from "../src/host/node/deepgram-voice-session.js";
import { createElevenLabsVoiceSessionSpeechProvider,ElevenLabsVoiceSessionSpeechProvider } from "../src/host/node/elevenlabs-voice-session-speech.js";
import { textToSpeechStreaming } from "../src/adapters/voice-tts.js";
import { VOICE_SESSION_VERSION,type VoiceIdentity } from "../src/console/voice-session-contract.js";
import { VoiceSessionRuntime,type VoiceTranscriptionCallbacks } from "../src/console/voice-session-runtime.js";

const identity:VoiceIdentity={session_id:"session-provider-example",capture_id:"capture-provider-example",delivery_id:"delivery-provider-example",subject_agent_id:"agent-example"};
class FakeSocket extends EventEmitter implements RealtimeSocket{readyState=0;sent:Array<string|Buffer>=[];send(data:string|Buffer){this.sent.push(data);}close(){this.readyState=3;this.emit("close",1000,Buffer.alloc(0));}providerClose(code:number,reason:string){this.readyState=3;this.emit("close",code,Buffer.from(reason));}open(){this.readyState=1;this.emit("open");}message(value:unknown){this.emit("message",Buffer.from(JSON.stringify(value)));}}
class FakeTimerScheduler implements VoiceProviderTimerScheduler{
	intervals:Array<{callback:()=>void;milliseconds:number;active:boolean}>=[];
	timeouts:Array<{callback:()=>void;milliseconds:number;active:boolean}>=[];
	interval(callback:()=>void,milliseconds:number){const timer={callback,milliseconds,active:true};this.intervals.push(timer);return()=>{timer.active=false;};}
	timeout(callback:()=>void,milliseconds:number){const timer={callback,milliseconds,active:true};this.timeouts.push(timer);return()=>{timer.active=false;};}
	fireInterval(index=0){const timer=this.intervals[index];if(timer?.active)timer.callback();}
	fireTimeout(index=0){const timer=this.timeouts[index];if(timer?.active){timer.active=false;timer.callback();}}
	fireActiveTimeout(milliseconds:number){const index=this.timeouts.findIndex((timer)=>timer.active&&timer.milliseconds===milliseconds);assert.notEqual(index,-1,`missing active ${milliseconds}ms timer`);this.fireTimeout(index);}
}
function callbacksFor(overrides:Partial<VoiceTranscriptionCallbacks>={}):VoiceTranscriptionCallbacks{return{
	speechStarted(){},speechResumed(){},partial(){},segmentFinal(){},thoughtCommitted(){},error(){},...overrides,
};}
const socket=new FakeSocket();let observedURL="";let observedAuthorization="";
const partials:string[]=[];const segments:string[]=[];const thoughts:string[]=[];let speechStarted=0;let speechResumed=0;const errors:string[]=[];
const provider=new DeepgramVoiceTranscriptionProvider("server-secret",(url,headers)=>{observedURL=url;observedAuthorization=headers.Authorization;return socket;});
const session=provider.open(identity,callbacksFor({speechStarted(){speechStarted++;},speechResumed(){speechResumed++;},partial(text){partials.push(text);},segmentFinal(text){segments.push(text);},thoughtCommitted(text){thoughts.push(text);},error(code){errors.push(code);}}));
session.append(Buffer.alloc(640));assert.equal(socket.sent.length,0,"audio queues until provider is ready");socket.open();assert.equal(Buffer.isBuffer(socket.sent[0]),true);assert.match(observedURL,/encoding=linear16/);assert.match(observedURL,/sample_rate=16000/);assert.equal(observedAuthorization,"Token server-secret");
socket.message({type:"SpeechStarted"});socket.message({type:"Results",start:0,duration:0.2,channel_index:[0,1],is_final:false,speech_final:false,channel:{alternatives:[{transcript:"hello"}]}});socket.message({type:"Results",start:0,duration:0.5,channel_index:[0,1],is_final:true,speech_final:false,channel:{alternatives:[{transcript:"hello there"}]}});session.finish();assert.deepEqual(socket.sent.at(-1),JSON.stringify({type:"Finalize"}));socket.message({type:"Results",start:0.5,duration:0.5,channel_index:[0,1],is_final:true,speech_final:true,channel:{alternatives:[{transcript:"friend"}]}});
assert.equal(speechStarted,1);assert.equal(speechResumed,0);assert.deepEqual(partials,["hello","hello there","hello there friend"]);assert.deepEqual(segments,["hello there","friend"]);assert.deepEqual(thoughts,["hello there friend"]);assert.deepEqual(errors,[]);

let batchURL="";let batchAuthorization="";let batchContentType="";let batchBody=Buffer.alloc(0);let batchReady=0;let batchSpeechStarted=0;const batchSegments:string[]=[];const batchThoughts:string[]=[];const batchErrors:Array<{code:string;retryable:boolean}>=[];
const batchProvider=new DeepgramVoiceTranscriptionProvider("server-secret",()=>{throw new Error("batch path cannot open a realtime socket");},{batchFetchImplementation:async(input,init)=>{batchURL=String(input);batchAuthorization=new Headers(init?.headers).get("authorization")||"";batchContentType=new Headers(init?.headers).get("content-type")||"";batchBody=Buffer.from(init?.body as Uint8Array);return new Response(JSON.stringify({results:{channels:[{alternatives:[{transcript:"prerecorded request"}]}]}}),{status:200,headers:{"content-type":"application/json"}});}});
const batchSession=batchProvider.openRecording(identity,callbacksFor({ready(){batchReady++;},speechStarted(){batchSpeechStarted++;},segmentFinal(text){batchSegments.push(text);},thoughtCommitted(text){batchThoughts.push(text);},error(code,retryable){batchErrors.push({code,retryable});}}));
batchSession.append(Buffer.alloc(640,0x2a));batchSession.append(Buffer.alloc(320,0x2b));batchSession.finish();for(let index=0;index<20&&batchThoughts.length===0;index++)await new Promise((resolve)=>setTimeout(resolve,1));
assert.match(batchURL,/https:\/\/api\.deepgram\.com\/v1\/listen/);assert.match(batchURL,/encoding=linear16/);assert.equal(batchAuthorization,"Token server-secret");assert.equal(batchContentType,"audio/l16");assert.equal(batchBody.byteLength,960);assert.equal(batchReady,1);assert.equal(batchSpeechStarted,1);assert.deepEqual(batchSegments,["prerecorded request"]);assert.deepEqual(batchThoughts,["prerecorded request"]);assert.deepEqual(batchErrors,[]);
const cancelledBatchThoughts:string[]=[];const cancelledBatch=batchProvider.openRecording(identity,callbacksFor({thoughtCommitted(text){cancelledBatchThoughts.push(text);}}));cancelledBatch.append(Buffer.alloc(640));cancelledBatch.finish();cancelledBatch.cancel();await new Promise((resolve)=>setTimeout(resolve,0));assert.deepEqual(cancelledBatchThoughts,[],"cancelled prerecorded results cannot create canonical work");

const continuationSocket=new FakeSocket();const continuationTimers=new FakeTimerScheduler();const continuationSegments:string[]=[];const continuationThoughts:string[]=[];let continuationResumes=0;
const continuationSession=new DeepgramVoiceTranscriptionProvider("server-secret",()=>continuationSocket,{timerScheduler:continuationTimers}).open(identity,callbacksFor({speechResumed(){continuationResumes++;},segmentFinal(text){continuationSegments.push(text);},thoughtCommitted(text){continuationThoughts.push(text);}}));
continuationSocket.open();continuationSession.append(Buffer.alloc(640,4));continuationSocket.message({type:"SpeechStarted"});continuationSocket.message({type:"Results",start:0,duration:0.5,channel_index:[0,1],is_final:true,speech_final:true,channel:{alternatives:[{transcript:"first segment"}]}});
assert.deepEqual(continuationSegments,["first segment"]);assert.deepEqual(continuationThoughts,[],"segment final cannot authorize delivery");assert.equal(continuationSocket.readyState,1,"provider remains open during continuation grace");
const staleDeadline=continuationTimers.timeouts.find((timer)=>timer.milliseconds===DEEPGRAM_THOUGHT_CONTINUATION_MILLISECONDS.speechFinal)!;assert.equal(staleDeadline.active,true);continuationSocket.message({type:"SpeechStarted"});assert.equal(continuationResumes,1);assert.equal(staleDeadline.active,false);const deadlineCountBeforeInterim=continuationTimers.timeouts.length;continuationSocket.message({type:"Results",is_final:false,speech_final:false,channel:{alternatives:[{transcript:"continued"}]}});assert.equal(continuationTimers.timeouts.length,deadlineCountBeforeInterim,"resumed interim preview cannot re-arm thought commitment");staleDeadline.callback();continuationTimers.timeouts.filter((timer)=>timer.active).forEach((timer)=>timer.callback());assert.deepEqual(continuationThoughts,[],"elapsed time after resumed interim cannot commit the old thought");assert.equal(continuationSocket.readyState,1,"resumed interim keeps the provider stream open");
const continuedFinal={type:"Results",start:1,duration:0.5,channel_index:[0,1],is_final:true,speech_final:true,channel:{alternatives:[{transcript:"continued thought"}]}};continuationSocket.message(continuedFinal);const finalDeadlineCount=continuationTimers.timeouts.length;continuationSocket.message(continuedFinal);assert.equal(continuationTimers.timeouts.length,finalDeadlineCount,"exact final-result replay cannot extend commitment");continuationSocket.message({type:"UtteranceEnd"});
assert.deepEqual(continuationSegments,["first segment","continued thought"],"exact final-result replay cannot duplicate committed text");assert.deepEqual(continuationThoughts,[]);continuationTimers.fireActiveTimeout(DEEPGRAM_THOUGHT_CONTINUATION_MILLISECONDS.utteranceEnd);assert.deepEqual(continuationThoughts,["first segment continued thought"]);assert.equal(continuationResumes,1);continuationTimers.timeouts.filter((timer)=>timer.active).forEach((timer)=>timer.callback());assert.equal(continuationThoughts.length,1,"one provider thought commits once");

const raceSocket=new FakeSocket();const raceTimers=new FakeTimerScheduler();const raceThoughts:string[]=[];const racePreparedTexts:string[]=[];
const raceIdentity:VoiceIdentity={session_id:"session-interim-race",capture_id:"capture-interim-race",delivery_id:"delivery-interim-race",subject_agent_id:"agent-example"};
const raceProvider=new DeepgramVoiceTranscriptionProvider("server-secret",()=>raceSocket,{timerScheduler:raceTimers});
const raceRuntime=new VoiceSessionRuntime({inputWindow:2,transcription:{open(providerIdentity,providerCallbacks){return raceProvider.open(providerIdentity,{...providerCallbacks,thoughtCommitted(text){raceThoughts.push(text);providerCallbacks.thoughtCommitted(text);}});}},canonical:{async prepare(input){racePreparedTexts.push(input.text);return{completionID:"completion-interim-race",async dispatch(){async function* partials(){}return{partials:partials(),final:Promise.resolve({text:"answer",speechEligible:false})};}};}}});
raceRuntime.open("agent-example",{version:VOICE_SESSION_VERSION,identity:raceIdentity,audio:{encoding:"pcm_s16le",sample_rate:16_000,channel_count:1},configuration:{response_policy:"standard",speech_mode:"silent"}});raceSocket.open();
await raceRuntime.applyClientEvent("agent-example",raceIdentity.session_id,{version:VOICE_SESSION_VERSION,identity:raceIdentity,sequence:1,kind:"audio",audio:Buffer.alloc(640,8).toString("base64"),duration_milliseconds:20});
const raceFirstFinal={type:"Results",start:0,duration:0.5,channel_index:[0,1],is_final:true,speech_final:true,channel:{alternatives:[{transcript:"first segment"}]}};raceSocket.message({type:"SpeechStarted"});raceSocket.message(raceFirstFinal);await new Promise((resolve)=>setTimeout(resolve,0));
raceSocket.message({type:"SpeechStarted"});raceSocket.message({type:"Results",start:0.5,duration:0.3,channel_index:[0,1],is_final:false,speech_final:false,channel:{alternatives:[{transcript:"still speaking"}]}});const raceDeadlineCount=raceTimers.timeouts.length;raceSocket.message(raceFirstFinal);assert.equal(raceTimers.timeouts.length,raceDeadlineCount,"replayed old final cannot re-arm after resumed interim");raceSocket.message({type:"UtteranceEnd"});raceTimers.fireActiveTimeout(DEEPGRAM_THOUGHT_CONTINUATION_MILLISECONDS.segmentFinal);await new Promise((resolve)=>setTimeout(resolve,0));
assert.deepEqual(raceThoughts,[],"unresolved interim cannot emit thoughtCommitted after UtteranceEnd timeout");assert.deepEqual(racePreparedTexts,[],"unresolved interim boundary cannot authorize canonical prepare");assert.equal(raceSocket.readyState,3,"unresolved provider boundary fails closed after its bound");const raceBoundaryEvents=raceRuntime.poll(raceIdentity.session_id,0).events;assert.equal(raceBoundaryEvents.at(-1)?.error_code,"transcription_provider_timeout");assert.equal(raceBoundaryEvents.some((event)=>event.kind==="transcript_final"||event.kind==="send_accepted"),false);

const manualSocket=new FakeSocket();const manualTimers=new FakeTimerScheduler();const manualThoughts:string[]=[];const manualPreparedTexts:string[]=[];
const manualIdentity:VoiceIdentity={session_id:"session-interim-manual",capture_id:"capture-interim-manual",delivery_id:"delivery-interim-manual",subject_agent_id:"agent-example"};
const manualProvider=new DeepgramVoiceTranscriptionProvider("server-secret",()=>manualSocket,{timerScheduler:manualTimers});
const manualRuntime=new VoiceSessionRuntime({inputWindow:2,transcription:{open(providerIdentity,providerCallbacks){return manualProvider.open(providerIdentity,{...providerCallbacks,thoughtCommitted(text){manualThoughts.push(text);providerCallbacks.thoughtCommitted(text);}});}},canonical:{async prepare(input){manualPreparedTexts.push(input.text);return{completionID:"completion-interim-manual",async dispatch(){async function* partials(){}return{partials:partials(),final:Promise.resolve({text:"answer",speechEligible:false})};}};}}});
manualRuntime.open("agent-example",{version:VOICE_SESSION_VERSION,identity:manualIdentity,audio:{encoding:"pcm_s16le",sample_rate:16_000,channel_count:1},configuration:{response_policy:"standard",speech_mode:"silent"}});manualSocket.open();
await manualRuntime.applyClientEvent("agent-example",manualIdentity.session_id,{version:VOICE_SESSION_VERSION,identity:manualIdentity,sequence:1,kind:"audio",audio:Buffer.alloc(640,9).toString("base64"),duration_milliseconds:20});
manualSocket.message({type:"SpeechStarted"});manualSocket.message({type:"Results",start:0,duration:0.5,channel_index:[0,1],is_final:true,speech_final:true,channel:{alternatives:[{transcript:"first segment"}]}});await new Promise((resolve)=>setTimeout(resolve,0));manualSocket.message({type:"SpeechStarted"});manualSocket.message({type:"Results",start:0.5,duration:0.3,channel_index:[0,1],is_final:false,speech_final:false,channel:{alternatives:[{transcript:"still speaking"}]}});
await manualRuntime.applyClientEvent("agent-example",manualIdentity.session_id,{version:VOICE_SESSION_VERSION,identity:manualIdentity,sequence:2,kind:"end_of_utterance"});manualSocket.message({type:"Results",start:0.5,duration:0.3,channel_index:[0,1],is_final:true,speech_final:true,channel:{alternatives:[{transcript:""}]}});await new Promise((resolve)=>setTimeout(resolve,0));
assert.deepEqual(manualThoughts,[],"manual finalize plus empty final cannot commit older segments");assert.deepEqual(manualPreparedTexts,[],"manual empty final cannot authorize canonical prepare");assert.equal(manualSocket.readyState,1,"manual finalize waits for the unresolved matching final");assert.equal(manualRuntime.poll(manualIdentity.session_id,0).events.some((event)=>event.kind==="transcript_final"||event.kind==="send_accepted"),false);
const manualFinal={type:"Results",start:0.5,duration:0.3,channel_index:[0,1],is_final:true,speech_final:true,channel:{alternatives:[{transcript:"continued thought"}]}};manualSocket.message(manualFinal);for(let index=0;index<20&&manualPreparedTexts.length===0;index++)await new Promise((resolve)=>setTimeout(resolve,1));
assert.deepEqual(manualThoughts,["first segment continued thought"]);assert.deepEqual(manualPreparedTexts,["first segment continued thought"]);assert.equal(manualRuntime.poll(manualIdentity.session_id,0).events.filter((event)=>event.kind==="transcript_final").length,1);assert.equal(manualSocket.readyState,3);

const coordinateSocket=new FakeSocket();const coordinateTimers=new FakeTimerScheduler();const coordinateSegments:string[]=[];const coordinateThoughts:string[]=[];const coordinateErrors:string[]=[];
new DeepgramVoiceTranscriptionProvider("server-secret",()=>coordinateSocket,{timerScheduler:coordinateTimers}).open(identity,callbacksFor({segmentFinal(text){coordinateSegments.push(text);},thoughtCommitted(text){coordinateThoughts.push(text);},error(code){coordinateErrors.push(code);}}));coordinateSocket.open();coordinateSocket.message({type:"SpeechStarted"});coordinateSocket.message({type:"Results",start:0,duration:0.5,channel_index:[0,1],is_final:true,speech_final:true,channel:{alternatives:[{transcript:"immutable segment"}]}});coordinateSocket.message({type:"Results",start:0,duration:0.5,channel_index:[0,1],is_final:true,speech_final:true,channel:{alternatives:[{transcript:"changed segment"}]}});
assert.deepEqual(coordinateSegments,["immutable segment"]);assert.deepEqual(coordinateThoughts,[]);assert.deepEqual(coordinateErrors,["transcription_invalid_response"]);assert.equal(coordinateSocket.readyState,3,"changed text at one provider coordinate fails closed");

const earlyCloseSocket=new FakeSocket();const earlyErrors:string[]=[];const earlyPartials:string[]=[];const earlySession=new DeepgramVoiceTranscriptionProvider("server-secret",()=>earlyCloseSocket).open(identity,callbacksFor({partial(text){earlyPartials.push(text);},error(code){earlyErrors.push(code);}}));earlySession.append(Buffer.alloc(640,7));earlyCloseSocket.close();earlyCloseSocket.open();earlyCloseSocket.message({type:"Results",is_final:false,channel:{alternatives:[{transcript:"late"}]}});assert.deepEqual(earlyErrors,["transcription_provider_unavailable"]);assert.equal(earlyCloseSocket.sent.length,0,"late open never forwards queued failed-session microphone audio");assert.deepEqual(earlyPartials,[],"late provider messages are ignored after failure");
class ThrowingSocket extends FakeSocket{send(){throw new Error("synthetic send failure");}close(){this.readyState=3;throw new Error("synthetic close failure");}}const throwingSocket=new ThrowingSocket();const throwingErrors:string[]=[];const throwingSession=new DeepgramVoiceTranscriptionProvider("server-secret",()=>throwingSocket).open(identity,callbacksFor({error(code){throwingErrors.push(code);}}));throwingSocket.open();assert.doesNotThrow(()=>throwingSession.append(Buffer.alloc(32)));assert.deepEqual(throwingErrors,["transcription_provider_unavailable"]);assert.doesNotThrow(()=>throwingSession.cancel());

const rejectedSocket=new FakeSocket();const rejectedErrors:string[]=[];const diagnostics:Array<Record<string,unknown>>=[];
new DeepgramVoiceTranscriptionProvider("server-secret",()=>rejectedSocket,{
	runtimeIdentity:"runtime-example-0001",sourceIdentity:"1111111111111111111111111111111111111111",requestID:()=>"request-example-0001",
	onHandshakeDiagnostic(diagnostic){diagnostics.push(diagnostic);},
}).open(identity,callbacksFor({error(code){rejectedErrors.push(code);}}));
const rejectedResponse=new EventEmitter() as IncomingMessage;rejectedResponse.statusCode=409;rejectedResponse.statusMessage="Conflict";
rejectedSocket.emit("unexpected-response",{},rejectedResponse);rejectedResponse.emit("data",Buffer.from(JSON.stringify({err_code:"CONFLICT",message:`Token ${"s".repeat(48)} for owner@example.com at https://provider.example.com/private`})));rejectedResponse.emit("end");
assert.deepEqual(rejectedErrors,["transcription_provider_unavailable"]);assert.equal(diagnostics.length,1);assert.equal(diagnostics[0].http_status,409);assert.equal(diagnostics[0].response_category,"CONFLICT");assert.equal(diagnostics[0].request_correlation,"request-example-0001");assert.match(String(diagnostics[0].session_correlation),/^sha256:[0-9a-f]{24}$/);assert.equal(diagnostics[0].runtime_identity,"runtime-example-0001");assert.equal(diagnostics[0].source_identity,"1111111111111111111111111111111111111111");assert.ok(String(diagnostics[0].response_excerpt).length<=512);assert.doesNotMatch(JSON.stringify(diagnostics),/session-provider-example|owner@example\.com|provider\.example\.com|s{32}/);

const preAudioSocket=new FakeSocket();const preAudioTimers=new FakeTimerScheduler();const preAudioErrors:string[]=[];
const preAudioSession=new DeepgramVoiceTranscriptionProvider("server-secret",()=>preAudioSocket,{timerScheduler:preAudioTimers}).open(identity,callbacksFor({error(code){preAudioErrors.push(code);}}));
preAudioSocket.open();assert.equal(preAudioTimers.intervals[0]?.milliseconds,4_000);assert.equal(preAudioTimers.timeouts[0]?.milliseconds,60_000);assert.deepEqual(preAudioSocket.sent,[]);preAudioTimers.fireInterval();assert.deepEqual(preAudioSocket.sent,[JSON.stringify({type:"KeepAlive"})]);preAudioSession.append(Buffer.alloc(640,3));assert.equal(Buffer.isBuffer(preAudioSocket.sent.at(-1)),true);assert.equal(preAudioTimers.intervals[0]?.active,false);assert.equal(preAudioTimers.timeouts[0]?.active,false);const sentAfterAudio=preAudioSocket.sent.length;preAudioTimers.fireInterval();assert.equal(preAudioSocket.sent.length,sentAfterAudio,"pre-audio keepalive stops exactly when microphone audio begins");assert.deepEqual(preAudioErrors,[]);preAudioSession.cancel();

const idleTimeoutSocket=new FakeSocket();const idleTimeoutTimers=new FakeTimerScheduler();const idleTimeoutErrors:string[]=[];const idleTimeoutDiagnostics:Array<Record<string,unknown>>=[];
new DeepgramVoiceTranscriptionProvider("server-secret",()=>idleTimeoutSocket,{timerScheduler:idleTimeoutTimers,onHandshakeDiagnostic(diagnostic){idleTimeoutDiagnostics.push(diagnostic);}}).open(identity,callbacksFor({error(code){idleTimeoutErrors.push(code);}}));idleTimeoutSocket.open();idleTimeoutTimers.fireTimeout();assert.deepEqual(idleTimeoutErrors,["transcription_provider_timeout"]);assert.deepEqual(idleTimeoutDiagnostics.map(value=>value.outcome),["accepted","first_audio_timeout"]);assert.equal(idleTimeoutDiagnostics[1]?.response_category,"first_audio_timeout");

const postAcceptCloseSocket=new FakeSocket();const postAcceptErrors:string[]=[];const postAcceptDiagnostics:Array<Record<string,unknown>>=[];
new DeepgramVoiceTranscriptionProvider("server-secret",()=>postAcceptCloseSocket,{onHandshakeDiagnostic(diagnostic){postAcceptDiagnostics.push(diagnostic);}}).open(identity,callbacksFor({error(code){postAcceptErrors.push(code);}}));postAcceptCloseSocket.open();postAcceptCloseSocket.providerClose(1011,`NET-0001 no audio for Token ${"q".repeat(48)} owner@example.com https://provider.example.com/private`);assert.deepEqual(postAcceptErrors,["transcription_provider_unavailable"]);assert.deepEqual(postAcceptDiagnostics.map(value=>value.outcome),["accepted","closed_after_ready"]);assert.equal(postAcceptDiagnostics[1]?.close_code,1011);assert.equal(postAcceptDiagnostics[1]?.response_category,"NET-0001");assert.match(String(postAcceptDiagnostics[1]?.response_excerpt),/NET-0001/);assert.doesNotMatch(JSON.stringify(postAcceptDiagnostics),/owner@example\.com|provider\.example\.com|q{32}/);

const producedSegments:Array<{bytes:number;duration:number}>=[];let providerFormat="";
const speech=new ElevenLabsVoiceSessionSpeechProvider({apiKey:"server-secret",voiceId:"server-voice"},async(_text,config,onChunk)=>{providerFormat=config.outputFormat||"";onChunk(Buffer.alloc(48_000).toString("base64"));onChunk(Buffer.alloc(96).toString("base64"));});
await speech.stream({identity,completionID:"completion-example",text:"Speak this."},async(bytes,duration)=>{producedSegments.push({bytes:bytes.byteLength,duration});});
assert.equal(providerFormat,"pcm_24000");assert.deepEqual(producedSegments,[{bytes:48_000,duration:1_000},{bytes:96,duration:2}]);
let deliveredAfterCancel=0;let upstreamAborted=false;const cancelledSpeech=new ElevenLabsVoiceSessionSpeechProvider({apiKey:"server-secret",voiceId:"server-voice"},async(_text,_config,onChunk,signal)=>{cancelledSpeech.cancel(identity,"completion-cancelled");upstreamAborted=signal?.aborted===true;onChunk(Buffer.alloc(48).toString("base64"));});
await cancelledSpeech.stream({identity,completionID:"completion-cancelled",text:"Do not deliver."},async()=>{deliveredAfterCancel++;});assert.equal(deliveredAfterCancel,0);assert.equal(upstreamAborted,true);
class FakeTtsSocket extends EventEmitter{sent:string[]=[];throwOnSend=false;send(value:string){if(this.throwOnSend)throw new Error("synthetic tts send failure");this.sent.push(value);}close(){this.emit("close",1000,Buffer.alloc(0));}}
const sendSocket=new FakeTtsSocket();sendSocket.throwOnSend=true;const sendFailure=textToSpeechStreaming("hello",{apiKey:"server-secret",voiceId:"server-voice"},()=>{},undefined,{requireFinal:true,socketFactory:()=>sendSocket as any});sendSocket.emit("open");await assert.rejects(sendFailure,/send failed/);
const finalSocket=new FakeTtsSocket();let finalChunks=0;const finalPromise=textToSpeechStreaming("hello",{apiKey:"server-secret",voiceId:"server-voice"},()=>{finalChunks++;},undefined,{requireFinal:true,socketFactory:()=>finalSocket as any});finalSocket.emit("open");finalSocket.emit("message",Buffer.from(JSON.stringify({audio:Buffer.alloc(48).toString("base64"),isFinal:true})));finalSocket.emit("message",Buffer.from(JSON.stringify({audio:Buffer.alloc(48).toString("base64")})));await finalPromise;assert.equal(finalChunks,1,"messages queued after final are inert");
const falseFinalSocket=new FakeTtsSocket();const falseFinal=textToSpeechStreaming("hello",{apiKey:"server-secret",voiceId:"server-voice"},()=>{},undefined,{requireFinal:true,socketFactory:()=>falseFinalSocket as any});falseFinalSocket.emit("open");falseFinalSocket.emit("message",Buffer.from(JSON.stringify({isFinal:"false"})));falseFinalSocket.close();await assert.rejects(falseFinal,/closed before final/);
const abortSocket=new FakeTtsSocket();const abortController=new AbortController();const aborted=textToSpeechStreaming("hello",{apiKey:"server-secret",voiceId:"server-voice"},()=>{},abortController.signal,{requireFinal:true,socketFactory:()=>abortSocket as any});abortController.abort();abortSocket.emit("open");await aborted;assert.equal(abortSocket.sent.length,0,"abort before open prevents all provider sends");
const protectedRoot=mkdtempSync(join(tmpdir(),"voice-speech-config-"));try{const keyFile=join(protectedRoot,"key");const voiceFile=join(protectedRoot,"voice");writeFileSync(keyFile,"fixture-key\n",{mode:0o600});writeFileSync(voiceFile,"fixture-voice\n",{mode:0o600});assert.ok(createElevenLabsVoiceSessionSpeechProvider({MOM_ELEVENLABS_API_KEY_FILE:keyFile,MOM_ELEVENLABS_VOICE_ID_FILE:voiceFile}));}finally{rmSync(protectedRoot,{recursive:true,force:true});}
console.log("voice session provider tests passed");
