import assert from "node:assert/strict";
import { VOICE_SESSION_VERSION,type VoiceIdentity } from "../src/console/voice-session-contract.js";
import { VoiceSessionRuntime,type VoiceSpeechProvider } from "../src/console/voice-session-runtime.js";

const baseIdentity:VoiceIdentity={session_id:"session-corrective-base",capture_id:"capture-corrective-base",delivery_id:"delivery-corrective-base",subject_agent_id:"agent-example"};
const openFor=(identity:VoiceIdentity)=>({version:VOICE_SESSION_VERSION,identity,audio:{encoding:"pcm_s16le" as const,sample_rate:16000 as const,channel_count:1 as const},configuration:{response_policy:"standard" as const,speech_mode:"progressive_audio" as const}});
const canonical={async prepare(){return{completionID:"completion-corrective",async dispatch(){async function* partials(){yield{text:"answer",speechEligible:true};}return{partials:partials(),final:Promise.resolve({text:"answer",speechEligible:true})};}};}};
function runtimeFor(speech:VoiceSpeechProvider){return new VoiceSessionRuntime({inputWindow:2,speech,canonical,transcription:{open(_identity,callbacks){return{append(){},finish(){callbacks.segmentFinal("question");callbacks.thoughtCommitted("question");},cancel(){}};}}});}
async function finishCapture(runtime:VoiceSessionRuntime,identity:VoiceIdentity){runtime.open("agent-example",openFor(identity));await runtime.applyClientEvent("agent-example",identity.session_id,{version:VOICE_SESSION_VERSION,identity,sequence:1,kind:"end_of_utterance"});for(let index=0;index<20;index++)await new Promise((resolve)=>setTimeout(resolve,1));}

const emptyIdentity={...baseIdentity,session_id:"session-corrective-empty",capture_id:"capture-corrective-empty",delivery_id:"delivery-corrective-empty"};
const emptyRuntime=runtimeFor({async stream(){},cancel(){}});await finishCapture(emptyRuntime,emptyIdentity);const emptyEvents=emptyRuntime.poll(emptyIdentity.session_id,0).events;assert.equal(emptyEvents.at(-1)?.kind,"error");assert.equal(emptyEvents.at(-1)?.error_code,"speech_empty");assert.equal(emptyEvents.some((event)=>event.kind==="assistant_speech_completed"),false);

let release!:()=>void;const hold=new Promise<void>((resolve)=>{release=resolve;});
const cancelIdentity={...baseIdentity,session_id:"session-corrective-cancel",capture_id:"capture-corrective-cancel",delivery_id:"delivery-corrective-cancel"};
const cancelRuntime=runtimeFor({async stream(_input,onSegment){await onSegment(Buffer.alloc(48),1);await hold;},cancel(){release();throw new Error("synthetic speech cancel failure");}});await finishCapture(cancelRuntime,cancelIdentity);let events=cancelRuntime.poll(cancelIdentity.session_id,0).events;const started=events.find((event)=>event.kind==="assistant_speech_started");assert.ok(started?.speech_stream_id);const cancel={version:VOICE_SESSION_VERSION,identity:cancelIdentity,sequence:1,kind:"cancel" as const,completion_id:"completion-corrective",speech_stream_id:started.speech_stream_id,acknowledged_speech_segment_sequence:1};cancelRuntime.applySpeechControl("agent-example",cancelIdentity.session_id,cancel);cancelRuntime.applySpeechControl("agent-example",cancelIdentity.session_id,cancel);events=cancelRuntime.poll(cancelIdentity.session_id,0).events;assert.equal(events.filter((event)=>event.kind==="assistant_speech_cancelled").length,1,"exact cancel replay emits no second server event");

const throwingRuntime=(mode:"append"|"finish"|"cancel",identity:VoiceIdentity)=>new VoiceSessionRuntime({inputWindow:2,canonical,transcription:{open(){return{append(){if(mode==="append")throw new Error("synthetic append failure");},finish(){if(mode==="finish")throw new Error("synthetic finish failure");},cancel(){if(mode==="cancel"||mode==="append"||mode==="finish")throw new Error("synthetic cancel failure");}};}}});
const appendIdentity={...baseIdentity,session_id:"session-throw-append",capture_id:"capture-throw-append",delivery_id:"delivery-throw-append"};const appendRuntime=throwingRuntime("append",appendIdentity);appendRuntime.open("agent-example",{...openFor(appendIdentity),configuration:{response_policy:"standard",speech_mode:"silent"}});const appendEvent={version:VOICE_SESSION_VERSION,identity:appendIdentity,sequence:1,kind:"audio" as const,audio:Buffer.alloc(32).toString("base64"),duration_milliseconds:1};await appendRuntime.applyClientEvent("agent-example",appendIdentity.session_id,appendEvent);const appendEvents=appendRuntime.poll(appendIdentity.session_id,0).events;assert.equal(appendEvents.at(-1)?.error_code,"transcription_provider_failed");await appendRuntime.applyClientEvent("agent-example",appendIdentity.session_id,appendEvent);assert.deepEqual(appendRuntime.poll(appendIdentity.session_id,0).events,appendEvents);await assert.rejects(appendRuntime.applyClientEvent("agent-example",appendIdentity.session_id,{...appendEvent,sequence:2}),/event_after_terminal/);
const finishIdentity={...baseIdentity,session_id:"session-throw-finish",capture_id:"capture-throw-finish",delivery_id:"delivery-throw-finish"};const finishRuntime=throwingRuntime("finish",finishIdentity);finishRuntime.open("agent-example",{...openFor(finishIdentity),configuration:{response_policy:"standard",speech_mode:"silent"}});const finishEvent={version:VOICE_SESSION_VERSION,identity:finishIdentity,sequence:1,kind:"end_of_utterance" as const};await finishRuntime.applyClientEvent("agent-example",finishIdentity.session_id,finishEvent);const finishEvents=finishRuntime.poll(finishIdentity.session_id,0).events;assert.equal(finishEvents.at(-1)?.error_code,"transcription_provider_failed");await finishRuntime.applyClientEvent("agent-example",finishIdentity.session_id,finishEvent);assert.deepEqual(finishRuntime.poll(finishIdentity.session_id,0).events,finishEvents);
const inputCancelIdentity={...baseIdentity,session_id:"session-throw-cancel",capture_id:"capture-throw-cancel",delivery_id:"delivery-throw-cancel"};const inputCancelRuntime=throwingRuntime("cancel",inputCancelIdentity);inputCancelRuntime.open("agent-example",{...openFor(inputCancelIdentity),configuration:{response_policy:"standard",speech_mode:"silent"}});const inputCancelEvent={version:VOICE_SESSION_VERSION,identity:inputCancelIdentity,sequence:1,kind:"cancel" as const};await inputCancelRuntime.applyClientEvent("agent-example",inputCancelIdentity.session_id,inputCancelEvent);const inputCancelEvents=inputCancelRuntime.poll(inputCancelIdentity.session_id,0).events;assert.equal(inputCancelEvents.at(-1)?.kind,"cancelled");await inputCancelRuntime.applyClientEvent("agent-example",inputCancelIdentity.session_id,inputCancelEvent);assert.deepEqual(inputCancelRuntime.poll(inputCancelIdentity.session_id,0).events,inputCancelEvents);

const oversizedIdentity={...baseIdentity,session_id:"session-corrective-oversized",capture_id:"capture-corrective-oversized",delivery_id:"delivery-corrective-oversized"};
const oversizedText="x".repeat(65_537);const oversizedRuntime=new VoiceSessionRuntime({inputWindow:2,transcription:{open(_identity,callbacks){return{append(){},finish(){callbacks.segmentFinal("question");callbacks.thoughtCommitted("question");},cancel(){}};}},canonical:{async prepare(){return{completionID:"completion-oversized",async dispatch(){async function* partials(){yield{text:oversizedText,speechEligible:false};}return{partials:partials(),final:Promise.resolve({text:oversizedText,speechEligible:false})};}};}}});oversizedRuntime.open("agent-example",{...openFor(oversizedIdentity),configuration:{response_policy:"standard",speech_mode:"silent"}});await oversizedRuntime.applyClientEvent("agent-example",oversizedIdentity.session_id,{version:VOICE_SESSION_VERSION,identity:oversizedIdentity,sequence:1,kind:"end_of_utterance"});for(let index=0;index<20;index++)await new Promise((resolve)=>setTimeout(resolve,1));const oversizedEvents=oversizedRuntime.poll(oversizedIdentity.session_id,0).events;assert.equal(oversizedEvents.at(-1)?.kind,"error");assert.equal(oversizedEvents.some((event)=>event.text===oversizedText),false,"invalid assistant text is never persisted or emitted");

let stressRuntime!:VoiceSessionRuntime;const stressIdentity={...baseIdentity,session_id:"session-corrective-stress",capture_id:"capture-corrective-stress",delivery_id:"delivery-corrective-stress"};let partialCount=0;const stressSpeech:VoiceSpeechProvider={async stream(_input,onSegment){for(let segment=1;segment<=512;segment++){await onSegment(Buffer.alloc(48),1);const started=stressRuntime.poll(stressIdentity.session_id,0).events.find((event)=>event.kind==="assistant_speech_started")!;stressRuntime.applySpeechControl("agent-example",stressIdentity.session_id,{version:VOICE_SESSION_VERSION,identity:stressIdentity,sequence:segment,kind:"audio_accepted",completion_id:"completion-stress",speech_stream_id:started.speech_stream_id!,acknowledged_speech_segment_sequence:segment});}},cancel(){}};stressRuntime=new VoiceSessionRuntime({inputWindow:2,speech:stressSpeech,transcription:{open(_identity,callbacks){return{append(){partialCount++;callbacks.partial("p".repeat(partialCount));},finish(){callbacks.segmentFinal("question");callbacks.thoughtCommitted("question");},cancel(){}};}},canonical:{async prepare(){return{completionID:"completion-stress",async dispatch(){async function* partials(){yield{text:"answer",speechEligible:true};}return{partials:partials(),final:Promise.resolve({text:"answer",speechEligible:true})};}};}}});stressRuntime.open("agent-example",openFor(stressIdentity));const stressAudio=Buffer.alloc(32).toString("base64");for(let sequence=1;sequence<=2047;sequence++)await stressRuntime.applyClientEvent("agent-example",stressIdentity.session_id,{version:VOICE_SESSION_VERSION,identity:stressIdentity,sequence,kind:"audio",audio:stressAudio,duration_milliseconds:1});await stressRuntime.applyClientEvent("agent-example",stressIdentity.session_id,{version:VOICE_SESSION_VERSION,identity:stressIdentity,sequence:2048,kind:"end_of_utterance"});for(let index=0;index<100;index++){if(stressRuntime.poll(stressIdentity.session_id,0).terminal)break;await new Promise((resolve)=>setTimeout(resolve,1));}const stressEvents=stressRuntime.poll(stressIdentity.session_id,0).events;assert.equal(stressEvents.filter((event)=>event.kind==="assistant_speech_segment").length,512);assert.equal(stressEvents.at(-1)?.kind,"completed");assert.ok(stressEvents.length<=2048);
console.log("voice session corrective tests passed");
